drop table if exists "users";
create table "users"
(
    "userId"                  bigint not null generated by default as identity,
    "name"               varchar(255) null default null,
    "phoneNumber"            varchar(255) null default null,
    primary key ("userId")
);