apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-app
  labels:
    app: backend-app
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
        env: demo
    spec:
      containers:
      - name: backend-app
        image: localhost:5005/backend-app:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - name: app-config
          mountPath: /app/config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-user
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-database
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: backend-url
            path: bakend-url