apiVersion: auotoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 10